"""Email notification digest for the options premium-collection pipeline.

Separate email from swing_agent.notify (different subject prefix, different
content), reusing the same SMTP mechanism and the same GitHub Actions
secrets -- no new credentials anywhere. Designed to run headless: reads
whatever premium_agent.scan already wrote to reports/options/scan_<date>.json
(the fetch+scan step needs live Robinhood MCP access and runs separately,
in an interactive session/Routine -- see README's "Running the options
agent" section). This module does no Robinhood data fetching itself.

Environment variables (same GitHub Actions secrets swing_agent.notify uses):
  NOTIFY_EMAIL_FROM      sender address
  NOTIFY_EMAIL_PASSWORD  app password
  NOTIFY_EMAIL_TO        recipient address
  NOTIFY_SMTP_HOST       optional, default smtp.gmail.com
  NOTIFY_SMTP_PORT       optional, default 587
"""
from __future__ import annotations

import json
import os
import smtplib
import sys
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPORTS_DIR = ROOT / "reports" / "options"


def _fmt_trade(t: dict) -> str:
    return f"{t['symbol']} {t['type']} ${t['strike']:.2f} exp {t['expiration_date']}"


def _html_table(rows: list[list], headers: list[str]) -> str:
    th = "".join(f"<th style='padding:4px 10px;text-align:left;border-bottom:1px solid #ccc'>{h}</th>" for h in headers)
    body = ""
    for row in rows:
        td = "".join(f"<td style='padding:4px 10px'>{c}</td>" for c in row)
        body += f"<tr>{td}</tr>"
    return f"<table style='border-collapse:collapse;font-size:13px'><tr>{th}</tr>{body}</table>"


def render_html(report: dict) -> str:
    scan_date = report.get("scan_date", str(date.today()))
    eq = report.get("equity", {})
    starting = eq.get("starting_equity", 5000.0)
    csp_collateral = eq.get("csp_collateral", 0.0)
    shares_capital = eq.get("assigned_shares_capital", 0.0)
    capital_used = eq.get("capital_in_use", csp_collateral + shares_capital)
    available = eq.get("available_capital", starting)
    open_positions = report.get("open_positions", 0)

    parts = [f"""
<h2 style='font-family:sans-serif'>\U0001F4B0 Options Agent Daily Digest — {scan_date}</h2>
<p style='font-family:sans-serif;color:#555'>Paper trading summary (the wheel: cash-secured puts + covered calls). No real orders placed.</p>
<table style='font-family:sans-serif;font-size:13px;border-collapse:collapse;margin-bottom:12px'>
  <tr>
    <td style='padding:4px 16px 4px 0'><strong>Starting equity</strong></td>
    <td style='padding:4px 16px 4px 0'>${starting:,.2f}</td>
    <td style='padding:4px 16px 4px 0'><strong>Open positions</strong></td>
    <td style='padding:4px 0'>{open_positions}</td>
  </tr>
  <tr>
    <td style='padding:4px 16px 4px 0'><strong>Capital in use</strong></td>
    <td style='padding:4px 16px 4px 0'>${capital_used:,.2f} <span style='color:#999'>(${csp_collateral:,.2f} CSP + ${shares_capital:,.2f} shares)</span></td>
    <td style='padding:4px 16px 4px 0'><strong>Available (cap)</strong></td>
    <td style='padding:4px 0;color:{"#080" if available > 0 else "#c00"}'>${available:,.2f}</td>
  </tr>
</table>
"""]

    proposed = report.get("proposed", [])
    if proposed:
        rows = []
        for t in proposed:
            yield_pct = t.get("return_on_collateral_pct", t.get("static_return_pct", 0))
            rows.append([_fmt_trade(t), f"${t['credit']:.2f}", f"{t['delta']:.2f}",
                         f"{t['dte']}d", f"{yield_pct:.2f}%"])
        parts.append("<h3 style='font-family:sans-serif;color:#080'>\U0001F7E2 Proposed today</h3>")
        parts.append(_html_table(rows, ["Contract", "Credit", "Delta", "DTE", "Yield"]))
    else:
        parts.append("<p style='font-family:sans-serif'>\U0001F7E2 <strong>Proposed today:</strong> none</p>")

    skipped = report.get("skipped", {})
    if skipped:
        rows = [[sym, "; ".join(reasons)] for sym, reasons in skipped.items()]
        parts.append(
            f"<h3 style='font-family:sans-serif;color:#888'>⚪ Screened and skipped ({len(skipped)})</h3>"
        )
        parts.append(_html_table(rows, ["Symbol", "Reason"]))

    parts.append("""
<hr/>
<p style='font-family:sans-serif;color:#999;font-size:11px'>
  Generated by premium_agent -- paper mode only. No real capital at risk.
</p>
""")
    return "\n".join(parts)


def send_email(subject: str, html_body: str) -> bool:
    """Send email via SMTP. Returns True on success. Same mechanism and same
    secrets as swing_agent.notify.send_email -- this is a separate email
    (different subject/content), not a separate credential."""
    sender = os.environ.get("NOTIFY_EMAIL_FROM")
    password = os.environ.get("NOTIFY_EMAIL_PASSWORD")
    recipient = os.environ.get("NOTIFY_EMAIL_TO")
    smtp_host = os.environ.get("NOTIFY_SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.environ.get("NOTIFY_SMTP_PORT", "587"))

    if not all([sender, password, recipient]):
        print("NOTIFY_EMAIL_FROM / NOTIFY_EMAIL_PASSWORD / NOTIFY_EMAIL_TO not set — skipping email.",
              file=sys.stderr)
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls()
            server.login(sender, password)
            server.sendmail(sender, recipient, msg.as_string())
        print(f"Email sent to {recipient}")
        return True
    except Exception as e:
        print(f"Email failed: {e}", file=sys.stderr)
        return False


def latest_report(reports_dir: str | Path = REPORTS_DIR, as_of: date | None = None) -> dict | None:
    """Load today's reports/options/scan_<date>.json, written by
    premium_agent.scan. Returns None if today's fetch+scan hasn't run yet --
    the caller decides whether that's worth alerting on."""
    today = str(as_of or date.today())
    path = Path(reports_dir) / f"scan_{today}.json"
    if not path.exists():
        return None
    return json.loads(path.read_text())


def send_digest(report: dict) -> bool:
    scan_date = report.get("scan_date", str(date.today()))
    n_proposed = len(report.get("proposed", []))
    n_skipped = len(report.get("skipped", {}))
    subject = f"[Options Agent {scan_date}] {n_proposed} proposed · {n_skipped} skipped"
    html = render_html(report)
    return send_email(subject, html)


if __name__ == "__main__":
    report = latest_report()
    if report is None:
        print(f"No scan report for today ({date.today()}) — has premium_agent.scan run yet?", file=sys.stderr)
        sys.exit(1)
    send_digest(report)
